import os
import streamlit as st
import fitz  # PyMuPDF
from openai import OpenAI

"""Simple Chat‑with‑PDF app for Streamlit Cloud
-------------------------------------------------
Features
--------
• Upload a PDF
• Ask free‑form questions about its content
• Answers generated by OpenAI GPT models (e.g. gpt‑4o‑mini)

HOW IT WORKS
============
1. The PDF text is extracted with PyMuPDF and stored in `st.session_state`.
2. Each user question is sent to the model along with a system prompt that
   instructs it to answer **only** from the provided document text.
3. To keep the prompt within context limits, the document text is truncated
   to `MAX_CHARS`.

For production use on large PDFs you would typically:
   • split the document into chunks
   • generate embeddings (OpenAIEmbedding, LlamaIndex, etc.)
   • perform similarity search to retrieve only the most relevant chunks
   • send those chunks, not the whole document, to the model.
This minimalist version keeps things easy to understand.
"""

# ---------- Configuration ----------------------------------------------------
MAX_CHARS = 16000  # truncate doc to avoid context overflow (≈12‑13K tokens)
MODEL_NAME = "gpt-4o-mini"  # cheap+fast model; change to gpt‑4o or gpt‑3.5‑turbo

# Read API key ---------------------------------------------------------------
OPENAI_API_KEY = st.secrets.get("OPENAI_API_KEY") or os.getenv("OPENAI_API_KEY")
if not OPENAI_API_KEY:
    st.error("⚠️  Defina OPENAI_API_KEY em .streamlit/secrets.toml ou variável de ambiente")
    st.stop()

client = OpenAI(api_key=OPENAI_API_KEY)

# ---------- Helper functions -------------------------------------------------

def extract_pdf_text(uploaded_file: st.runtime.uploaded_file_manager.UploadedFile) -> str:
    """Return entire text of a PDF"""
    doc = fitz.open(stream=uploaded_file.read(), filetype="pdf")
    text = "".join(page.get_text() for page in doc)
    return text


def ask_gpt(question: str, context: str) -> str:
    """Ask OpenAI chat model with document context, return answer string"""
    system_prompt = (
        "Você é um assistente que responde somente com base no PDF fornecido. "
        "Se a resposta não estiver claramente presente no texto, diga educadamente que não sabe."
    )

    user_prompt = f"Documento:\n{context}\n\nPergunta do usuário: {question}"

    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        max_tokens=512,
        temperature=0.2,
    )
    return response.choices[0].message.content.strip()

# ---------- UI ----------------------------------------------------------------
st.set_page_config(page_title="Chat com PDF (OpenAI)", layout="centered")
st.title("📄 Chat com seu PDF usando IA")

uploaded_file = st.file_uploader("1️⃣  Faça upload do seu PDF", type="pdf")

if uploaded_file and "doc_text" not in st.session_state:
    with st.spinner("Extraindo texto do PDF …"):
        st.session_state.doc_text = extract_pdf_text(uploaded_file)[:MAX_CHARS]
    st.success("Texto carregado! Agora faça perguntas.")

if "doc_text" in st.session_state:
    if "messages" not in st.session_state:
        st.session_state.messages = []  # list of (role, content)

    # Display previous conversation
    for role, msg in st.session_state.messages:
        if role == "user":
            st.chat_message("user").write(msg)
        else:
            st.chat_message("assistant").write(msg)

    # Chat input
    user_q = st.chat_input("Digite sua pergunta sobre o PDF e pressione Enter…")
    if user_q:
        st.session_state.messages.append(("user", user_q))
        st.chat_message("user").write(user_q)

        with st.spinner("Consultando IA…"):
            answer = ask_gpt(user_q, st.session_state.doc_text)
        st.session_state.messages.append(("assistant", answer))
        st.chat_message("assistant").write(answer)

else:
    st.info("📥  Primeiro, envie um PDF para iniciar o chat.")
